language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_ebd5a4459d6a_key -iv $encrypted_ebd5a4459d6a_iv  -in deploy_key.enc -out deploy_key -d
- wget http://www.icy.bioimageanalysis.org/downloadIcy/icy.zip && unzip icy.zip -d  icy && rm icy.zip
script:
- ant icyhlplugininstaller
after_success:
- eval "$(ssh-agent -s)" 
- chmod 600 deploy_key
- ssh-add deploy_key
- git config --global user.email "ferreol.soulez@univ-lyon1.fr"
- git config --global user.name "ferreolS"
- git config --global push.default matching
- git clone  --branch=jar git@github.com:ferreolS/${PROJECT}
- cp -r jar/* ${PROJECT}
- cd ${PROJECT} && git add * && git commit -am "Jar update" && git push --force
env:
  global:
  - PROJECT=icyhlplugininstaller
