anguage: java
jdk:
- oraclejdk7
before_install:
# First icy dependies
- wget http://www.icy.bioimageanalysis.org/downloadIcy/icy.zip && unzip icy.zip -d icy && rm icy.zip
- cd ..
- mkdir lib
- mkdir bin
- mv icy/icy.jar lib/
- mv icy/lib/bioformats.jar lib/
- mv icy/plugins/adufour/blocks/Blocks.jar lib/
- mv icy/plugins/adufour/ezplug/EzPlug.jar lib/
- mv icy/plugins/adufour/protocols/Protocols.jar lib/
# prepare for build
- git clone --quiet --branch=master https://github.com/ferreolS/icyhlplugininstaller.git
- cd icyhlplugininstaller 

script:
- ant icyhlplugininstaller

after_succes:

- git config --global user.email "ferreol.soulez@epfl.ch.fr"
- git config --global user.name "ferreolS"
- git config --global push.default matching
- git clone --quiet --branch=gh-pages https://${GH_TOKEN}@github.com/emmt/${PROJECT}
- git clone  --branch=jars https://${GH_TOKEN}@github.com/ferreolS/${PROJECT}
- cp -r jar/* ${PROJECT}
- cd ${PROJECT} && git add * && git commit -am "Jar update" && (git push 2> /dev/null) 

env:
  global:
  - secure: G0VNj4mO734iePeYNDA0aqYy2mid4dBTEeupwmPEoGEf6yVMYgPrOLvYA0gJYD5MrUMZJ50tFIWWc9rWqsk8CTXCy8a3sAapQZma5TsggrnGOv6IK2emEHx9Znj4kdRRpX3MdxZhLwVTszUkejtoUOmAS4EOtUub4Ky7CUq0WJs=
  - PROJECT=icyhlplugininstaller